Create Book store testing.
Abdul-Rehman2134/BookStore-lara pull request #15
Opened 2022-04-12 09:08 UTC by Abdul-Rehman2134

2022-04-13 09:23 UTC, AhmedAlBaloshi requested changes

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/AuthorTest.php
> +    public function test_author_list()
change name to `test_list`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/AuthorTest.php
> +    public function test_author_add()
change name to `test_create`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/AuthorTest.php
> +    public function test_author_create()
change name to `test_store`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/AuthorTest.php
> +    public function test_author_edit()
`test_edit`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/AuthorTest.php
> +    public function test_author_update()
`test_update`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/AuthorTest.php
> +    public function test_author_destroy()
`test_destroy`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +    public function test_book()
`test_index`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +    public function test_book_detail()
test_view

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +    public function test_admin_add_book()
`test_create`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +    public function test_admin_book_store()
test_store

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +        $book = Book::factory()->create(['author_id' => $author->id, 'category_id' => $category->id]);
remove book factory in this test

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +            'name' => $book->name,
add data manualy in post form

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +    public function test_admin_edit_book()
test_edit

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +            ->assertSeeText('Name')
add assertion  for book columns

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +    public function test_admin_book_update()
test update

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +    public function test_admin_book_delete()
`test_destroy`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/BookTest.php
> +        // ->assertRedirect();
remove useless commits

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/CartTest.php
> +    public function test_example()
`test_index`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/CategoryTest.php
> +    public function test_category_list()
`test_list`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/CategoryTest.php
> +    public function test_category_add()
`test_create`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/CategoryTest.php
> +    public function test_category_create()
`test_store`

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/CategoryTest.php
> +        $category = Category::factory()->create();
In this case category factory is useless so remove it.

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/CategoryTest.php
> +                'name' => $category->name
add data manually

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/CategoryTest.php
> +    public function test_category_edit()
test_edit

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/CategoryTest.php
> +    public function test_category_update()
test_update

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/CategoryTest.php
> +                'name' => $category->name
add data manually

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/CategoryTest.php
> +    public function test_category_destroy()
test_destroy

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/ContactTest.php
> +    public function test_example()
test_index

2022-04-13 09:23 UTC, AhmedAlBaloshi commented on tests/Feature/HomeTest.php
> +    public function test_example()
test_index

2022-04-13 09:29 UTC, Abdul-Rehman2134 commented on tests/Feature/AuthorTest.php
> +    public function test_author_list()
done

2022-04-15 09:58 UTC, AhmedAlBaloshi approved these changes

2022-04-15 09:59 UTC, merged